% This is to test how much heat is generated by the battery for which
% components.
% Author: Volkan Kumtepeli

clear variables; close all; clc;
temp = load('../Q_table.txt'); 

time         = temp(:,1); % [s]

anode.Q_rxn  = temp(:,2); % Reaction (eta..)
anode.Q_rev  = temp(:,3); % Entropy
anode.Q_ohms = temp(:,4); % Solid phase
anode.Q_ohml = temp(:,5); % Liquid phase
anode.Q_ohm  = temp(:,6); % Total phase

cathode.Q_rxn  = temp(:,7); % Reaction (eta..)
cathode.Q_rev  = temp(:,8); % Entropy
cathode.Q_ohms = temp(:,9); % Solid phase
cathode.Q_ohml = temp(:,10); % Liquid phase
cathode.Q_ohm  = temp(:,11); % Total phase

% %% Anode vs Cathode: Q_{rxn}
% figure; hold on;
% plot(time, anode.Q_rxn, 'r', 'DisplayName', 'Anode Q_{rxn}');
% plot(time, cathode.Q_rxn, 'b--', 'DisplayName', 'Cathode Q_{rxn}');
% legend; xlabel('Time [s]'); ylabel('Q_{rxn}'); title('Q_{rxn}: Anode vs Cathode');
% 
% %% Anode vs Cathode: Q_{rev}
% figure; hold on;
% plot(time, anode.Q_rev, 'r', 'DisplayName', 'Anode Q_{rev}');
% plot(time, cathode.Q_rev, 'b--', 'DisplayName', 'Cathode Q_{rev}');
% legend; xlabel('Time [s]'); ylabel('Q_{rev}'); title('Q_{rev}: Anode vs Cathode');
% 
% %% Anode vs Cathode: Q_{ohms}
% figure; hold on;
% plot(time, anode.Q_ohms, 'r', 'DisplayName', 'Anode Q_{ohms}');
% plot(time, cathode.Q_ohms, 'b--', 'DisplayName', 'Cathode Q_{ohms}');
% legend; xlabel('Time [s]'); ylabel('Q_{ohms}'); title('Q_{ohms}: Anode vs Cathode');
% 
% %% Anode vs Cathode: Q_{ohml}
% figure; hold on;
% plot(time, anode.Q_ohml, 'r', 'DisplayName', 'Anode Q_{ohml}');
% plot(time, cathode.Q_ohml, 'b--', 'DisplayName', 'Cathode Q_{ohml}');
% legend; xlabel('Time [s]'); ylabel('Q_{ohml}'); title('Q_{ohml}: Anode vs Cathode');
% 
% %% Anode vs Cathode: Q_{ohm}
% figure; hold on;
% plot(time, anode.Q_ohm, 'r', 'DisplayName', 'Anode Q_{ohm}');
% plot(time, cathode.Q_ohm, 'b-', 'DisplayName', 'Cathode Q_{ohm}');
% legend; xlabel('Time [s]'); ylabel('Q_{ohm}'); title('Q_{ohm}: Anode vs Cathode');

%% Cumulative: Anode
figure;
%cs = [cumsum(anode.Q_rxn), cumsum(anode.Q_rev), cumsum(anode.Q_ohms), cumsum(anode.Q_ohml)];

%area(time, cs);

plot(time, cumsum(anode.Q_rxn), 'DisplayName', 'Q_{rxn}','LineWidth',2); hold on;
plot(time, cumsum(anode.Q_rev), 'DisplayName', 'Q_{rev}','LineWidth',2);
plot(time, cumsum(anode.Q_ohms), 'DisplayName', 'Q_{ohms}','LineWidth',2);
plot(time, cumsum(anode.Q_ohml), 'DisplayName', 'Q_{ohml}','LineWidth',2);
plot(time, cumsum(anode.Q_ohm), '--','DisplayName', 'Q_{ohm}','LineWidth',2);
legend; xlabel('Time [s]'); ylabel('Cumulative Q'); title('Cumulative Heat: Anode');
grid on;

%% Cumulative Area: Anode
% figure;
% cs = [cumsum(anode.Q_rxn), cumsum(anode.Q_rev), cumsum(anode.Q_ohms), cumsum(anode.Q_ohml)];
% 
% area(time, cs);

% area(time, cumsum(anode.Q_rxn), 'DisplayName', 'Q_{rxn}'); hold on;
% area(time, cumsum(anode.Q_rev), 'DisplayName', 'Q_{rev}');
% area(time, cumsum(anode.Q_ohms), 'DisplayName', 'Q_{ohms}');
% area(time, cumsum(anode.Q_ohml), 'DisplayName', 'Q_{ohml}');
%area(time, cumsum(anode.Q_ohm), 'DisplayName', 'Q_{ohm}');
% legend; xlabel('Time [s]'); ylabel('Cumulative Q'); title('Cumulative Heat: Anode');

%% Cumulative Area: Cathode
% % figure;
% % area(time, cumsum(cathode.Q_rxn), 'DisplayName', 'Q_{rxn}'); hold on;
% % area(time, cumsum(cathode.Q_rev), 'DisplayName', 'Q_{rev}');
% % area(time, cumsum(cathode.Q_ohms), 'DisplayName', 'Q_{ohms}');
% % area(time, cumsum(cathode.Q_ohml), 'DisplayName', 'Q_{ohml}');
% % area(time, cumsum(cathode.Q_ohm), 'DisplayName', 'Q_{ohm}');
% % legend; xlabel('Time [s]'); ylabel('Cumulative Q'); title('Cumulative Heat: Cathode');
% % 
% % %% Cumulative Area: Total (Anode + Cathode)
% % figure;
% % area(time, cumsum(anode.Q_rxn + cathode.Q_rxn), 'DisplayName', 'Q_{rxn}'); hold on;
% % area(time, cumsum(anode.Q_rev + cathode.Q_rev), 'DisplayName', 'Q_{rev}');
% % area(time, cumsum(anode.Q_ohms + cathode.Q_ohms), 'DisplayName', 'Q_{ohms}');
% % area(time, cumsum(anode.Q_ohml + cathode.Q_ohml), 'DisplayName', 'Q_{ohml}');
% % area(time, cumsum(anode.Q_ohm + cathode.Q_ohm), 'DisplayName', 'Q_{ohm}');
% % legend; xlabel('Time [s]'); ylabel('Cumulative Q'); title('Cumulative Heat: Total');
